NoxxDev/NecroBot

PoGo.NecroBot.ConfigUI/Models/ObservableSettings.cs

ConfigUI failed to compile due to type error. Fix the values from double to bool and compile successfully

Fix boolean values of variant walking

---

PoGo.NecroBot.CLI/App.config
PoGo.NecroBot.CLI/Program.cs
PoGo.NecroBot.ConfigUI/Models/ObservableSettings.cs

Conflict in Nuget produce error :
An unhandled exception of type 'System.AggregateException' occurred in mscorlib.dll
Removing the dependentAssembly of System.Net.Http fix this

Fix telegram issue

---

PoGo.NecroBot.CLI/Config/Translations/translation.id.json

Update Bahasa Indonesia

---

PoGo.NecroBot.Logic/Tasks/GetPokeDexCount.cs
PoGo.NecroBot.Logic/Tasks/TransferWeakPokemonTask.cs
PoGo.NecroBot.Logic/Tasks/UseIncenseConstantlyTask.cs
PoGo.NecroBot.Logic/Tasks/UseIncubatorsTask.cs
PoGo.NecroBot.Logic/Tasks/UseLuckyEggConstantlyTask.cs
PoGo.NecroBot.Logic/Tasks/UseNearbyPokestopsTask.cs

Almost all Tasks are public, except these 6. 
Can permanently fix https://github.com/vandernorth/NecroBot.GUI/issues/72
So it can be used by other bots, like mine :-)

Made tasks public that were internal or private

---

PoGo.NecroBot.CLI/PoGo.NecroBot.CLI.csproj
PoGo.NecroBot.Logic/PoGo.NecroBot.Logic.csproj

Just an help to make NecroBot.GUI able to compile without any problem

Using $(SolutionDir) instead of relative directory

---

PoGo.NecroBot.CLI/Config/Translations/translation.id.json

Make short and simple translating for Bahasa Indonesia.... Please check...

Bahasa Indonesia: fix and update translations.

---

PoGo.NecroBot.CLI/Config/Translations/translation.zh-TW.json

updata translation.zh-TW

---

PoGo.NecroBot.Logic/Strategies/Walk/GoogleStrategy.cs
PoGo.NecroBot.Logic/Utils/LocationUtils.cs

Fix of the extremely slow walking bug within the new google walking strategy

Fix of the extremely slow walking bug within the new google walking strategy (mixing [m/s] and [m])

---

PoGo.NecroBot.Logic/Event/UnaccurateLocation.cs
PoGo.NecroBot.Logic/PoGo.NecroBot.Logic.csproj
PoGo.NecroBot.Logic/Strategies/Walk/GoogleStrategy.cs
PoGo.NecroBot.Logic/Utils/LocationUtils.cs

Now the bot doesn't walk in straight line in large roads, there is a "inacuratte" calc from Geopoint
The Gps from Phone don't get same lat lng if u stay stoped and no one walks in straight line, for this reason I have changed the walk style, now It's look like:

Enhancement from gps with google walk strategy.

---

PoGo.NecroBot.Logic/Model/Settings/CustomCatchConfig.cs

Turns on missed throws by default.

Turn on missed throws by default for humanization.

---

PoGo.NecroBot.CLI/PoGo.NecroBot.CLI.csproj
PoGo.NecroBot.CLI/WebSocketHandler/ActionCommands/FavoritePokemonHandler.cs
PoGo.NecroBot.Logic/Tasks/FavoritePokemonTask.cs

Allow UI to favorite pokemon through socket

Socket: UI ask for favorite

---

PoGo.NecroBot.CLI/Config/Translations/translation.id.json

Update translation according to the newest reference.

Bahasa Indonesia: update translation.

---

PoGo.NecroBot.CLI/Config/Translations/translation.de.json

I found conflict, means deleted the translation for Killswitches, see https://github.com/NoxxDev/NecroBot/pull/422
Will something similar to them added later?

Reworked -> Update translation.de.json

---

PoGo.NecroBot.Logic/Model/Settings/GlobalSettings.cs

configuring transfer filter: choose best moves
> Question: what is diffirent between frostBreathFast and frostBreath ?

transfer-filter choose best moves

---

PoGo.NecroBot.CLI/PoGo.NecroBot.CLI.csproj
PoGo.NecroBot.CLI/WebSocketHandler/ActionCommands/DropItemHandler.cs
PoGo.NecroBot.Logic/Tasks/RecycleItemsTask.cs

Alloàw UI to drop item through a socket event.
https://github.com/nicoschmitt/necrobotvisualizer/issues/159

Allow UI to drop item

---

PoGo.NecroBot.CLI/Config/Translations/translation.it.json

The second value is temporary (i don't know how to translate it yet :')

Updated IT translation

---

PoGo.NecroBot.CLI/Config/Translations/translation.it.json

I found out how to translate it ;)

 Right IT translation

---

NecroBot for Pokemon Go.sln
PoGo.NecroBot.CLI/ConsoleEventListener.cs
PoGo.NecroBot.Logic/Common/Translations.cs
PoGo.NecroBot.Logic/Event/HumanWalkSnipeEvent.cs
PoGo.NecroBot.Logic/Interfaces/Configuration/ILogicSettings.cs
PoGo.NecroBot.Logic/Model/Settings/GlobalSettings.cs
PoGo.NecroBot.Logic/Model/Settings/HumanWalkSnipeConfig.cs
PoGo.NecroBot.Logic/Model/Settings/HumanWalkSnipeFilter.cs
PoGo.NecroBot.Logic/Model/Settings/LogicSettings.cs
PoGo.NecroBot.Logic/PoGo.NecroBot.Logic.csproj
PoGo.NecroBot.Logic/Tasks/HumanWalkSnipeTask.cs
PoGo.NecroBot.Logic/Tasks/UseNearbyPokestopsTask.cs

Hi, 
I would like to ask you merge this PR . basically it allow bot fetch data from skiplagged and pokeradar to find local rare pokemon (in your filter list) and walk to catch them. you can see our test & discussion here.
https://github.com/NoxxDev/NecroBot/issues/398
Thanks

New Feature human walk snipe

---

PoGo.NecroBot.Logic/Model/Settings/GlobalSettings.cs

just a small mistake in code that make filter config reset any time file change. please merge this PR. thanks

fix config reset issue

---

README.md

extra information about snipping options

extra information about snipping options

---

PoGo.NecroBot.CLI/ConsoleEventListener.cs
PoGo.NecroBot.Logic/Common/Translations.cs
PoGo.NecroBot.Logic/Event/HumanWalkSnipeEvent.cs
PoGo.NecroBot.Logic/Interfaces/Configuration/ILogicSettings.cs
PoGo.NecroBot.Logic/Model/Settings/HumanWalkSnipeConfig.cs
PoGo.NecroBot.Logic/Model/Settings/HumanWalkSnipeFilter.cs
PoGo.NecroBot.Logic/Model/Settings/LogicSettings.cs
PoGo.NecroBot.Logic/Tasks/CatchIncensePokemonsTask.cs
PoGo.NecroBot.Logic/Tasks/CatchNearbyPokemonsTask.cs
PoGo.NecroBot.Logic/Tasks/HumanWalkSnipeTask.cs
PoGo.NecroBot.Logic/Tasks/UseNearbyPokestopsTask.cs

there pull request to fix few issue that people reported today
- add config to turn off/of live map (pokeradar, skiplagged)
- turn of snipe in GPX mode
- change message when not enought ball
- add config to not using list pokemon to snip

Humal walk snipe bug fix/enhancement

---

PoGo.NecroBot.Logic/Tasks/FarmPokestopsTask.cs
PoGo.NecroBot.Logic/Tasks/UseNearbyPokestopsTask.cs

just in case we got API exception,  the bot will continue at the current place. because some time walk snipe will make bot walk so far base on config then it good to make them stay at the current point.

logic adjustment to make bot work with snipe

---

PoGo.NecroBot.CLI/Program.cs
PoGo.NecroBot.Logic/State/StateMachine.cs

I found it lost "subPath" In PoGo.NecroBot.Logic.State.StateMachine, when I want to use one exe for multi bot.

Fix for multi bot (config)

---

README.md

msniper link updated

---

PoGo.NecroBot.Logic/Tasks/UseNearbyPokestopsTask.cs

Parent FarmPokestopsGPXTask (only) calls
CatchNearbyPokemonsTask.Execute
CatchIncensePokemonsTask.Execute
UseNearbyPokestopsTask.Execute
Above happens while moving. Solution: check for lures in this module, and before doing
the other actions. The reason behind the bug could be cooldowns caused by the other tasks
leading to CatchLurePokemons not taking effect. This solution has been tested and works afaik.
+ also indented some other code here for better readability.

Fix for bug where lured Pokemons aren't caught when using GPX (#324)

---

README.md

necrobot screen view

---

PoGo.NecroBot.Logic/Tasks/SnipeMSniperTask.cs

sometimes we send wrong PokemonName from msniper to necrobot, so bot trying to deserialize but can not.
Also msniper mustn't use with HumanWakingSpine, SnipeAtPokestops and UseSnipeLocationServer, its not safety, so logic has been updated

MSniper JsonDeserialize bug fixed

---

PoGo.NecroBot.CLI/Config/Translations/translation.id.json

Fix translations.id.json can not load on the first start.

Fix translations.id.json can not load on the first start.

---

PoGo.NecroBot.CLI/Config/Translations/translation.id.json

Update translation for Bahasa Indonesia

Update translation.id.json for First Start More + AutoComplete Tutorial

---

PoGo.NecroBot.Logic/Tasks/FarmPokestopsGPXTask.cs

Set initial values for resume variables to null

---

PoGo.NecroBot.Logic/Tasks/CatchNearbyPokemonsTask.cs
PoGo.NecroBot.Logic/Tasks/SnipeMSniperTask.cs

bug fixed,
now exactly working what we need
reference issue https://github.com/NoxxDev/NecroBot/issues/808

MSniper 'Did not find a Pokemon error' solution

---

PoGo.NecroBot.CLI/WebSocketHandler/ActionCommands/SetConfigHandler.cs
PoGo.NecroBot.Logic/Model/Settings/AuthSettings.cs
PoGo.NecroBot.Logic/Model/Settings/GlobalSettings.cs
PoGo.NecroBot.Logic/Model/Settings/Location.cs
PoGo.NecroBot.Logic/Model/Settings/SnipeSettings.cs
PoGo.NecroBot.Logic/Model/Settings/TransferFilter.cs

Add DefaultValueHandling.Ignore for object with no DefaultValue
attribute

Minor addition to merged PR#809

---

PoGo.NecroBot.Logic/Strategies/Walk/BaseWalkStrategy.cs
PoGo.NecroBot.Logic/Strategies/Walk/FlyStrategy.cs
PoGo.NecroBot.Logic/Strategies/Walk/GoogleStrategy.cs
PoGo.NecroBot.Logic/Strategies/Walk/HumanPathWalkingStrategy.cs
PoGo.NecroBot.Logic/Strategies/Walk/HumanStrategy.cs
PoGo.NecroBot.Logic/Strategies/Walk/IWalkStrategy.cs
PoGo.NecroBot.Logic/Strategies/Walk/YoursNavigationStrategy.cs
PoGo.NecroBot.Logic/Tasks/HumanWalkSnipeTask.cs

Calculates the true distance between 2 points using Google/Yours walking strategies for human snipe instead of simple estimation by multiplying by constant 1.5

Bug fix - Add proper distance calculation when using Google or Yours strategies

---

PoGo.NecroBot.Logic/Model/Settings/PlayerConfig.cs

Fixing JSerializationException due to default null value.

Fixing JSerializationException due to default null value.

---

PoGo.NecroBot.Logic/Strategies/Walk/BaseWalkStrategy.cs
PoGo.NecroBot.Logic/Strategies/Walk/FlyStrategy.cs
PoGo.NecroBot.Logic/Strategies/Walk/GoogleStrategy.cs
PoGo.NecroBot.Logic/Strategies/Walk/HumanPathWalkingStrategy.cs
PoGo.NecroBot.Logic/Strategies/Walk/HumanStrategy.cs
PoGo.NecroBot.Logic/Strategies/Walk/IWalkStrategy.cs
PoGo.NecroBot.Logic/Strategies/Walk/YoursNavigationStrategy.cs
PoGo.NecroBot.Logic/Tasks/UseNearbyPokestopsTask.cs

count distance by walking path not by straight line distance

count distance by walking path

---

PoGo.NecroBot.Logic/Tasks/SnipeMSniperTask.cs

Short Description: 
bug fixed, codes cleanup
Fixes :
msniper location bug fixed, now pokemons can catchable

MSniper minor location bug fixed

---

PoGo.NecroBot.CLI/Program.cs
PoGo.NecroBot.CLI/SniperEventListener.cs
PoGo.NecroBot.GUI/PoGo.NecroBot.GUI.csproj
PoGo.NecroBot.Logic/Event/HumanWalkSnipeEvent.cs
PoGo.NecroBot.Logic/Event/SnipePokemonFoundEvent.cs
PoGo.NecroBot.Logic/Interfaces/Configuration/ILogicSettings.cs
PoGo.NecroBot.Logic/Model/Settings/HumanWalkSnipeConfig.cs
PoGo.NecroBot.Logic/Model/Settings/HumanWalkSnipeFilter.cs
PoGo.NecroBot.Logic/Model/Settings/ItemRecycleConfig.cs
PoGo.NecroBot.Logic/Model/Settings/LogicSettings.cs
PoGo.NecroBot.Logic/PoGo.NecroBot.Logic.csproj
PoGo.NecroBot.Logic/Tasks/HumanWalkSnipeTask.FastPokemap.cs
PoGo.NecroBot.Logic/Tasks/HumanWalkSnipeTask.PokeZZ.cs
PoGo.NecroBot.Logic/Tasks/HumanWalkSnipeTask.Pokecrew.cs
PoGo.NecroBot.Logic/Tasks/HumanWalkSnipeTask.Pokeradar.cs
PoGo.NecroBot.Logic/Tasks/HumanWalkSnipeTask.Pokesnipers.cs
PoGo.NecroBot.Logic/Tasks/HumanWalkSnipeTask.Skiplagged.cs
PoGo.NecroBot.Logic/Tasks/HumanWalkSnipeTask.cs
PoGo.NecroBot.Logic/Tasks/RecycleItemsTask.cs
PoGo.NecroBot.Logic/Tasks/SnipePokemonTask.cs

Since Pokeradar giving wrong data feed, I added support for fastpokemap which is more reliable . Also many people request to have human snipe work with pogolocation feeder. is now include in this pull request
- Add support Fastpokemap.se data feed
- add support PogolocationFeeder.
Cheers

Human walk snipe with PogolocationFeeder & Fastpokemap.se data feed 

---

PoGo.NecroBot.Logic/Model/Settings/EvolveConfig.cs

Fix Pokemons To Evolve Default List

Fix Pokemons To Evolve Default List

---

PoGo.NecroBot.CLI/PoGo.NecroBot.CLI.csproj
PoGo.NecroBot.CLI/WebSocketHandler/ActionCommands/ForceUsePokestop.cs
PoGo.NecroBot.CLI/WebSocketHandler/ActionCommands/SetMoveToTarget.cs
PoGo.NecroBot.Logic/PoGo.NecroBot.Logic.csproj
PoGo.NecroBot.Logic/Tasks/SetMoveToTargetTask.cs
PoGo.NecroBot.Logic/Tasks/UseNearbyPokestopsTask.cs

Add Set Destination in websocket feature for Visualizer Tool  .
Add PoGo.NecroBot.CLI\WebSocketHandler\SetDestinationHandler.cs
Modify PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs
Online Visualizer Tool : http://hassenlin.byethost12.com/
Source : https://github.com/HassenLin/necrobotvisualizer

Add  websocket Command  "SetMoveToTarget";

---

PoGo.NecroBot.Logic/Tasks/CatchLurePokemonsTask.cs
PoGo.NecroBot.Logic/Tasks/CatchPokemonTask.cs

Fixed #881:  Candy Display on Lure Catch
Fixed #900:  Missed Throw Odds Calculation

Fixed #881:  Candy Display on Lure Catch
